# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_ubio_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_ubio_project'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_ubio_project:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    # sources:
    #   +name: sources
    #   database: production
    #   +schema: public
    #   table : customertable
    #   +materialized: table
    mart:
      name: mart
      +materialized: table
      
    staging:
      +name: staging
      materialized: table
  

